language: java

jdk:
- oraclejdk8

script: ./gradlew clean build

after_success:
- ./gradlew jacocoRootReport coveralls --continue

#notifications:
#  slack:
#    rooms:
#      - codecentric:i0Ekrt5ujN7hHqmZviq64SsI#gareth
